version: '3.8'

services:
  database:
    image: postgres:15
    container_name: database
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  # auth-service:
  #   build:
  #     context: ./auth-service
  #   container_name: auth-service
  #   restart: always
  #   ports:
  #     - "8081:8081"
  #   depends_on:
  #     - database
  #   env_file:
  #     - ./auth-service/.env

volumes:
  pgdata:
